apiVersion: apps/v1
kind: Deployment
metadata:
  name: revhire-user
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: revhire-user
  template:
    metadata:
      labels:
        app : revhire-user
    spec:
      volumes:
      - name: aws-secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: aws-secrets
      containers:
        - name: revhire-user
          image: public.ecr.aws/a6p3b4m6/revhire-user-service:latest
          env: 
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: aws-secrets
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: aws-secrets
                key: password  
          - name: DB_PORT  
            valueFrom:
              secretKeyRef:
                 name: aws-secrets
                 key: port
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                 name: aws-secrets
                 key: host 
---
apiVersion: v1
kind: Service
metadata:
  name: revhire-user-service
  labels:
    app: revhire-user
spec:
  selector:
    app: revhire-user
  ports:
    - protocol: 'TCP'
      port: 8082
      targetPort: 8082
  type: LoadBalancer